csv_input_file: 'node.csv'
csv_split_output_file: 'csv_split_output.csv'
csv_combine_output_file: 'csv_combine_output.csv'
font_path: 'MontserratAlternates-Thin.ttf'
image_directory_path: 'C:/Users/zxx91/Desktop/DSU_googleAPI/'
GOOGLE_APPLICATION_CREDENTIALS: 'inner-legacy-412817-c457e22e9329.json'
