csv_input_file: 'node.csv'
csv_output_file: 'output.csv'
font_path: 'MontserratAlternates-Thin.ttf'
image_directory_path: 'C:\\Users\\zxx91\\Desktop\\DSU_googleAPI\\'
GOOGLE_APPLICATION_CREDENTIALS: 'inner-legacy-412817-c457e22e9329.json'
MODE: 'json_pdf' # use <'download'> first, and chose output mode <'json'>, <'pdf'>, <'json_pdf'>/<'pdf_json'>